name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10
  - pip=22.3.1
  # - pytorch=2.0.1
  # - torchaudio=0.15.2
  # - torchvision=2.0.2
  # - tqdm
  # - pip:
  #   - submodules/diff-gaussian-rasterization
  #   - submodules/simple-knn
  #   - submodules/fused-ssim
  #   - opencv-python
  #   - joblib
  #   - open3d
  #   - polyscope
  #   - porpourri3d
